---
version: "3.8"
services:
  devlength:
    image: slabs:latest
    container_name: slabs
    #env_file:
    #  - ./EDIT.env
    #ports:
    #  - 9000:8501
    restart: unless-stopped
    networks:
      - cloudflare-tunnel

networks:
  cloudflare-tunnel:
    external: true
    name: cloudflare-tunnel
