---
version: "2.1"
services:
  devlength:
    image: ${NAME}:latest
    container_name: ${NAME}
    env_file:
      - ./EDIT.env
    #ports:
    #  - 9000:8501
    restart: unless-stopped
networks:
  default:
    external:
        name: cloudflare-tunnel